#!/bin/bash
#
# Unstage all .html and .pdf files that share the same basename as a .Rmd file
# which resides in the same directory, and add said files to the .gitignore 

# if there is no newline at the end of .gitignore add it
if [[ ! (-s .gitignore && -z "$(tail -c 1 .gitignore)") ]]; then
    echo '' >> .gitignore
fi
extensions=(pdf html docx)
while IFS= read -r -d '' file <&9; do
	filename="${file%.*}"
	for ext in ${extensions[@]}; do
		generated_file="$filename.$ext"
		if [[ $(git restore --staged "$generated_file" 2>/dev/null) ]]; then 
			echo ignore-knit: Unstaging "$generated_file"
		fi 
		
		if [[ ! $(git check-ignore "$generated_file" 2>/dev/null) ]]; then
		    echo "$generated_file" >> .gitignore
			echo "Adding $generated_file to .gitignore"
		fi
	done;
done 9< <(git diff --staged --name-only -z --diff-filter=AR '*.[Rr][Mm][Dd]') 
git add .gitignore